### ISSUE TITLE
Build Harnessing (2024)

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/electrical-projects#10]
# [E-10] Build Harnessing 2024
## Description
Physically build the tractor wire harnessing for our 2024 tractor

## Tasks
- [ ] Determine materials list
- [ ] Purchase any materials we need
- [ ] Assemble harnessing
- [ ] Validate harness (continuity testing)

#### Requires
- 
- https://github.com/umatt-ece/electrical-projects/issues/2
