### ISSUE TITLE
Harness Drawings (2024)

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/electrical-projects#11]
# [E-11] Harness Drawings (2024)
## Description
We need to design and create harness drawings for our 2024 tractor.

## Tasks
- [ ] Control Board harnessing
- [ ] Relay Board harnessing
- [ ] Sevcon harnessing
- [ ] Ignition & Engine harnessing
- [ ] Generator & Contactor harnessing
- [ ] High-voltage Indication harnessing
- [ ] Electric Motor harnessing
- [ ] Transmission harnessing
- [ ] Pump & Fan harnessing
- [ ] Differential (including linear actuator) harnessing
- [ ] Miscellaneous sensors harnessing

#### Requires
- https://github.com/umatt-ece/electrical-projects/issues/3

#### Blocks
- https://github.com/umatt-ece/electrical-projects/issues/10

#### Related
- https://github.com/umatt-ece/electrical-projects/issues/2
