### ISSUE TITLE
RPM Sensor

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/electrical-projects#12]
# [E-12] RPM Sensor
## Description
We want to install a speed sensor on the tractor (that measures pulses of a spinning 'gear' on the driveshaft) in order to measure the speed of the driveshaft in RPM.

## Tasks
- [ ] Find/Purchase sensor
- [ ] Create harnessing for sensor
- [ ] Determine mounting for sensor
- [ ] Create software issue to read sensor data

#### Blocks
- 

#### Related
-
