### ISSUE TITLE
Build Backup Control Board

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/electrical-projects#16]
# [E-16] Build Backup Control Board
## Description
We should build a secondary control board. This would give us experience with PCB design, a better understanding of the control board, and a backup board for if anything happens at competition.

## Tasks
- [ ] Update PCB schematics (if required)
- [ ] Order PCB boards
- [ ] Order PCB components
- [ ] Build PCB board
- [ ] Test PCB board
