### ISSUE TITLE
Drivetrain Test Bench

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/electrical-projects#4]
# Drivetrain Test Bench

## Description

We would like to set up a drivetrain test bench for easier testing of the Sevcon during the year (when the tractor might not be in a running state). Minimally we need:

- power source for the sevcon (can use old combustion engine from previous years with electric generator)
- sevcon gen4 motor controller (can take the current one off the tractor)
- electric motor
- a way to read electric motor output (speed sensor or visual indicator)
- required harnessing
- physical mount for equipment
- ***safety switches and adequate fusing***

## Tasks
- [ ] Write formal report for proposed drivetrain test bench
- [ ] Purchase required equipment for the test bench
- [ ] Assemble and Test
