### ISSUE TITLE
Investigate Sevcon

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/electrical-projects#5]
# Investigate Sevcon
## Description
Realistically, we don't know all that much about the Sevcon Gen4 Motor Controller (Size 6) we are using. Further investigation is required in order to more fully understand how to operate it.

## Tasks
- [ ] Power on the Sevcon
- [ ] Connect CAN reader
- [ ] "Mock" the interlock inputs (ex. use RPi Controller + Relay Board)
- [ ] Connect & test 3-phase output to the electric motor
- [ ] Document our knowledge of how to operate the Sevcon

## Additional Notes
- [Sevcon Manual](https://www.thunderstruck-ev.com/images/Gen4%20Product%20Manual%20V3%204.pdf)

**Comment by Kameroni33** [comment]
As of July 26, 2023 we were able to power it on (got a solid green light) using the combustion engine and electric generator.

Additionally, here are some sketches & notes on the wiring of the Sevcon:

![image](https://github.com/umatt-ece/electrical-projects/assets/65875945/239ef800-95a8-4f45-a9bc-e4195d59471b)

![image](https://github.com/umatt-ece/electrical-projects/assets/65875945/6cf4a4e3-4615-4ba3-814d-a327fb1fa53e)

![image](https://github.com/umatt-ece/electrical-projects/assets/65875945/4c0114cd-cd78-4c91-b361-c37ac7f685a8)
