### ISSUE TITLE
Fix Relay Board

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/electrical-projects#7]
# Fix Relay Board
## Description
A few of the LED’s burnt out on the relay board during competition 2023, which need to be replaced. I thought this a good opportunity to gain some experience reprinting the board, and maybe making a few minor changes:
1. Try to make the board more compact (moving components closer together)
2. Update the printed labelling to be more general (not tie us to using certain outputs for certain operations, but allow us to play with it and change up the wiring if we want to).

Additionally, I think it would be nice to have a fully functional second board, so we can keep one for testing.

## Tasks
- [ ] Review the current design of the Relay Board
- [ ] Make the described changes to the Relay Board
- [ ] Make pull request for updated board design
- [ ] Order PCB
- [ ] Purchase board components
- [ ] Fix LED’s on current board
- [ ] Assemble second Relay Board
