### ISSUE TITLE
Alternative Project Management Tools

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/electrical-projects#9]
# [E-9] Investigate other Project Management Tools
## Description
Currently we are using GitHub as a project management tool of choice. We chose this because all of our code was already hosted on GitHub and it made sense to limit the amount of different software we were using. GitHub does a fairly good job of it, but it can be lacking in certain areas. There are other software programs out there that are dedicated to Project Management and do a very good job at it. I think we should investigate some of these and see if we think it would be worth while to switch to another platform.

## Tasks
- [ ] Determine criteria for evaluating Project Management Software
- [ ] Investigate [Jira](https://www.atlassian.com/software/jira) (by [Atlassian](https://www.atlassian.com/))
- [ ] Investigate [YouTrack](https://www.jetbrains.com/youtrack/) (by [JetBrains](https://www.jetbrains.com/))
- [ ] Research other Project Management Software
- [ ] Compile Results into a single _finding document_
- [ ] Make decision if a change of platform is feasible and/or worth it

## Linked Issues
- 

### Evaluation Criteria
1.
